/**
 * 省份打卡配置
 * state: 'done' | 'soon' | 'planned' | 'unplanned'
 * viewPermission: 'public' | 'name'  （已打卡时有效）
 * allowedNameHashes: 当 viewPermission 为 'name' 时，允许查看的姓名 SHA-256 哈希（hex）列表，非明文
 * media: 已打卡时的媒体资源，路径相对于 /public/media/
 */

export const STATE_DONE = 'done'       // 已打卡
export const STATE_SOON = 'soon'       // 即将打卡
export const STATE_PLANNED = 'planned' // 规划中
export const STATE_UNPLANNED = 'unplanned' // 未规划

export const STATE_LABELS = {
  [STATE_DONE]: '已打卡',
  [STATE_SOON]: '即将打卡',
  [STATE_PLANNED]: '规划中',
  [STATE_UNPLANNED]: '未规划',
}

/** ECharts 地图中省份中文名 → 配置 key（拼音） */
export const provinceNameToKey = {
  北京: 'beijing',
  天津: 'tianjin',
  河北: 'hebei',
  山西: 'shanxi',
  内蒙古: 'neimenggu',
  辽宁: 'liaoning',
  吉林: 'jilin',
  黑龙江: 'heilongjiang',
  上海: 'shanghai',
  江苏: 'jiangsu',
  浙江: 'zhejiang',
  安徽: 'anhui',
  福建: 'fujian',
  江西: 'jiangxi',
  山东: 'shandong',
  河南: 'henan',
  湖北: 'hubei',
  湖南: 'hunan',
  广东: 'guangdong',
  广西: 'guangxi',
  海南: 'hainan',
  重庆: 'chongqing',
  四川: 'sichuan',
  贵州: 'guizhou',
  云南: 'yunnan',
  西藏: 'xizang',
  陕西: 'shaanxi',
  甘肃: 'gansu',
  青海: 'qinghai',
  宁夏: 'ningxia',
  新疆: 'xinjiang',
  台湾: 'taiwan',
  香港: 'hongkong',
  澳门: 'macao',
}

export const mapConfig = {
  beijing: {
    name: '北京',
    state: STATE_DONE,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [
      { type: 'image', src: 'media/beijing/1.jpg', title: '故宫' },
    ],
  },
  tianjin: {
    name: '天津',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  hebei: {
    name: '河北',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  shanxi: {
    name: '山西',
    state: STATE_SOON,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  neimenggu: {
    name: '内蒙古',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  liaoning: {
    name: '辽宁',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  jilin: {
    name: '吉林',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  heilongjiang: {
    name: '黑龙江',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  shanghai: {
    name: '上海',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  jiangsu: {
    name: '江苏',
    state: STATE_DONE,
    viewPermission: 'name',
    allowedNameHashes: ['6592320e7f47c8fc4c5e83ca2a915afb3cb602eee359b33464ebc05a42e710d7'],
    media: [],
  },
  zhejiang: {
    name: '浙江',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  anhui: {
    name: '安徽',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  fujian: {
    name: '福建',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  jiangxi: {
    name: '江西',
    state: STATE_DONE,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  shandong: {
    name: '山东',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  henan: {
    name: '河南',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  hubei: {
    name: '湖北',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  hunan: {
    name: '湖南',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  guangdong: {
    name: '广东',
    state: STATE_DONE,
    viewPermission: 'name',
    allowedNameHashes: ['9bbed60271e479879951e0ab35ffc81f1958099e3b4643661c4f58eb6fd049d2'],
    media: [],
  },
  guangxi: {
    name: '广西',
    state: STATE_PLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  hainan: {
    name: '海南',
    state: STATE_PLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  chongqing: {
    name: '重庆',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  sichuan: {
    name: '四川',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  guizhou: {
    name: '贵州',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  yunnan: {
    name: '云南',
    state: STATE_PLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  xizang: {
    name: '西藏',
    state: STATE_PLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  shaanxi: {
    name: '陕西',
    state: STATE_SOON,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  gansu: {
    name: '甘肃',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  qinghai: {
    name: '青海',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  ningxia: {
    name: '宁夏',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  xinjiang: {
    name: '新疆',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  taiwan: {
    name: '台湾',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  hongkong: {
    name: '香港',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
  macao: {
    name: '澳门',
    state: STATE_UNPLANNED,
    viewPermission: 'public',
    allowedNameHashes: [],
    media: [],
  },
}
